import localFont from "next/font/local";
import "./globals.css";
import {Outfit} from "next/font/google"


export const metadata = {
  title: "YangStone | AI Note Talking",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        {children}
      </body>
    </html>
  );
}
